### ISSUE TITLE
Make a real webapp to replace current command line demo.js

### ISSUE THREAD

**Issue by kevingzhang** [elastos/Elastos.NET.Carrier.Nodejs.SDK#10]
The current demo.js is just a clone from the linux shell command line demo app (shell app). We should make a better looking, more professional looking demo app.

**Comment by jmsaulnier** [comment]
Can you confirm if it makes sense to use socket connection? https://github.com/jmsaulnier/Elastos.NET.Carrier.Nodejs.SDK/tree/feature/demo-socket/example/demo

Thanks

**Comment by kevingzhang** [comment]
@jmsaulnier , what do you mean by socket connection? socket between who and who? 
If what you meant was to connect person A and person B, then this is not the problem Carrier is supposed to solve. Carrier solved the problem that both (or one of ) A and B are inside firewall, so that there is no way to make direct connection. If A and B are all public IP, there is no need for Carrier. In most cases, most of users are behind a firewall (or gateway) using NAT or something like that to access public internet.

**Comment by jmsaulnier** [comment]
@kevingzhang I mean, how do you plan to communicate between node.js to call elastos carrier native function and the webapp?

**Comment by kevingzhang** [comment]
Oh, i see. Webapp use whatever to call node.js (Websocket, http, https). Node.js call node-add-on library (installed by NPM) to access carrier native function. 
See the demo.js app for the nodejs part. 
Demo.js is a terminal app, no front end. That's why I ask Clarence to make a web app to use the node.js backend.

**Comment by ClarenceL** [comment]
Yep will work on a boilerplate for this on Sunday

**Comment by jmsaulnier** [comment]
@ClarenceL Looking forward to check it out 🤓

**Comment by kevingzhang** [comment]
@liyangwood Has started the project. Please work on the same project. do not duplicate work. See his commit in web-demo branch

**Comment by kevingzhang** [comment]
I will assign this issue to @liyangwood , He will be the main contributor. @ClarenceL Please help him to polish the code structure to be more formal.

**Comment by liyangwood** [comment]
we already build a prototype web demo for now. please get more details from the beneath link.
https://github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK/tree/web_demo/example/web-chat-demo
