### ISSUE TITLE
I think it is possible to wrap the multi-clients in node.js level not in C++ level

### ISSUE THREAD

**Issue by kevingzhang** [elastos/Elastos.NET.Carrier.Nodejs.SDK#11]
I see the code
`var carrier = carrierSdk.createObject(opts, callbacks);
carrier.on("idle", idle_callback); //add idle event
carrier.on("idle", null); //delete idle event

carrier.run();
// carrier.destory();

`
I think we can do the multiple clients support in NOde.js level. No need to change C++.
We can create the carrier instance from a client login event. Then return the carrierID back to client. The client will call the node.js server everytime with the CarrierID. 

You just need to build a CarrierManger object to host all carriers with the CarrierID as the index.

I will assign this issue to a js developer so that they are family with node.js programming.

**Comment by kevingzhang** [comment]
I suggest we save no profile information in Carrier. I prefer to leave the logic of user profile to DApp itself. Carrier only care about the user ID, nothing else.

**Comment by kuit** [comment]
The carrier must save a profile,  it save the user node_id, user_id etc. If the profile is deleted, then the user can't use the old user_id.
In the carriermanger section should manger the profile, the DApp don't care the profile。

**Comment by kuit** [comment]
OK.
Only one function:
carrier = CarrierManager.getCarrierInstance("user_id"); //if user_id is null, create new user_id。
But if the profile lose, the user_id is invalid.
The server must be save the profile, if not it don't work.

**Comment by kevingzhang** [comment]
If that's true, you have to modify the C++ code. When design the server, you cannot assume the client will always connect the same server every time. The load balancer will pick a server to response the client request randomly. If you save client A's profile in Server 1, but client A connect to Server 2 the next time, this will be a problem. 
In this case, the produce is not ready for server use yet. This is a big problem. You may have to fix this issue first before JS developer can jump in.

**Comment by kevingzhang** [comment]
If this issue cannot be fixed, then we have to run one server for one client. This is kind of odd.

**Comment by kuit** [comment]
We will provide three functions for web server.
1.When  client use his own user_id login, web server can user carrier = CarrierManager.getCarrierInstance("user_id")  to check the profile about this user_id. If the profile is exist, the function will return a carrier object. If not return a null object.
Web server can also use CarrierManager.getCarrierInstance(null) to create a new carrier object include a new user_id; 
2.If 1 is not exist profile, web server can use  CarrierManager.importProfile("user_id", zipfile_path) to import user profile to carriermanager. Then it can call CarrierManager.getCarrierInstance again.
3.Web server can backup the profile by CarrierManager.exportProfile("user_id", zipfile_path);

**Comment by kuit** [comment]
Maybe no need the CarrierManager.
Just use carrierSdk.createObj() function, it include the profile path argument.
Web server decide the id and profile relation. And it can provide profile download to client or upload from client function.

**Comment by kevingzhang** [comment]
Rather than file path, I prefer an object. Try to do everything in memory without file system. 
Can you write down the interface of those 3 functions?

**Comment by kevingzhang** [comment]
If everyone agree, I am going to close this issue.
