### ISSUE TITLE
🐛 Missing build folder (web-chat-demo-client branch)

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.NET.Carrier.Nodejs.SDK#12]
## Expected Behavior
Run web-chat-demo-client demo via npm start / npm run dev /  npm run build

## Actual Behavior
Can't run npm start / npm run dev /  npm run build 
Missing "build" folder error

## Steps to Reproduce the Problem

  1. cd example/web-chat-demo-client
  2. npm start

## How to resolve
Update .gitignore file  (there is a "build" on the .gitignore root project )

**Comment by kevingzhang** [comment]
Please add .gitignore and build folder

**Comment by kevingzhang** [comment]
A note to @jmsaulnier , another option is just to create a pull request since you already know the solution. 
Thank you very much @jmsaulnier. I am a Canadian too. I used to live in Victoria, BC before moved down to California. Nice to know you.

**Comment by jmsaulnier** [comment]
@kevingzhang yep I was thinking to send a PR, but with this type of issue, I thought it would be better to open an issue only

ps: I'm actually French, moved to Canada 5 years ago ^^, looking forward building stuffs with Elastos 👌

**Comment by kevingzhang** [comment]
Cool, we need people who can speak different languages. French of course is one of the popular languages we need. If there is anything related to French developer community, you may be very helpful.
thanks again.

**Comment by jmsaulnier** [comment]
@kevingzhang Any plans to create a Discord account for Elastos dev community?

**Comment by kevingzhang** [comment]
there is a Discord channel already. maintained by a community member, not me. Welcome to join that Discord channel.

**Comment by jmsaulnier** [comment]
@kevingzhang Invite links found on Reddit but doesn't seems working anymore. Would be great if there is an official one with dev from Elastos too

**Comment by kpachhai** [comment]
@jmsaulnier Try https://discord.gg/6QJ9NwQ

**Comment by liyangwood** [comment]
@jmsaulnier thanks for your issue.
Just fix it and hope you try again.
welcome to further more testing and find more problems.
