### ISSUE TITLE
carrier.getError is not defined

### ISSUE THREAD

**Issue by liyangwood** [elastos/Elastos.NET.Carrier.Nodejs.SDK#14]
When carrier instance occur an error, node.js wrapper will catch the error with getError method. but is not work for now, return the getError method is not defined.
```
"elastos_carrier_addon": "0.0.3",
```
Need to fix it.

**Comment by kuit** [comment]
Do you use "carrierSdk" to call getError()? "getError" is a utility function. Utility functions isn't  belong to carrier object.

**Comment by liyangwood** [comment]
@kuit Just call getError from node side. So I think this is node addon issue

**Comment by kevingzhang** [comment]
If it is related to document, please update the document too.

**Comment by kevingzhang** [comment]
Please always assign to someone to handle this issue. @liyangwood and @kuit  This is the rule

**Comment by kuit** [comment]
Document is right

**Comment by kevingzhang** [comment]
Then it is Jacky's mistake. @liyangwood please close the issue if it is fixed
