### ISSUE TITLE
👀 Save messages (web-demo branch)

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.NET.Carrier.Nodejs.SDK#16]
On the web-chat-demo https://github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK/tree/web_demo/example/web-chat-demo, we can send messages, but is these messages are save somewhere (.data folder? like profile information) ? so when you restart, messages are still there or this function is not included into Carrier and you will need something else?

**Comment by kevingzhang** [comment]
Carrier won't handle storage. This is not Carrier's design goal, neither the purpose of this demo app. 
The real chat app will need to store the offline message. However, this is out of our scope. Saving offline message has to be handled by other other, like IPFS or Application layer. Not Carrier.

**Comment by kevingzhang** [comment]
@jmsaulnier Please close this issue if you agreed with what I said
