### ISSUE TITLE
🐛 Typo function name: destory() → destroy() OR kill()

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.NET.Carrier.Nodejs.SDK#17]
## Expected Behavior
dest**ro**y()                                 = ela_kill
OR
kill()                                               = ela_kill

## Actual Behavior
dest**or**y()                                                   = ela_kill

## How to resolve
- Rename destory() to destroy() or kill() on SDK + demo folders  (any reason why it's not kill() like Native Carrier SDK: ela_kill ?)
- Publish new NPM module version

**Comment by kuit** [comment]
Fixed: destory() -> destroy()
Please update elastos_carrier_addon to version 0.0.4.

**Comment by kevingzhang** [comment]
@kuit Please do not close any issue not created by you. You can add your comments and assign to @jmsaulnier , if he confirmed it is fixed, he will close. You should not close it.

**Comment by kevingzhang** [comment]
Hi @jmsaulnier  I reopened this issue. Please verify what @kuit comment, if you confirmed, please close this issue. Sorry about that,

**Comment by kuit** [comment]
@kevingzhang got it.

**Comment by jmsaulnier** [comment]
@kuit any reason why it’s not kill() rather than destroy() ?

**Comment by kuit** [comment]
@jmsaulnier kill() should not use in carrier object. 
carrier.destroy() or carrierSdk.kill(carrier).
