### ISSUE TITLE
invite user is not working

### ISSUE THREAD

**Issue by liyangwood** [elastos/Elastos.NET.Carrier.Nodejs.SDK#22]
In example/demo, when use invite command like
```
invite BLkx8SkBpxxzM9dQwnTFtviboQidgvpAp8nk1CTTZo6Y hello
```
will return an error as below
```
Error:Run ela_invite_friend error:0x81000001
Send invite request failed(0x81000001).
```

**Comment by kuit** [comment]
It's a invalid arguments error. Maybe will support string error function in the future.
Errors define in the "ela_carrier.h" of carrier sdk.
Such as:

/******************************************************************************
 * Error handling
 *****************************************************************************/

#define ELASUCCESS                                0

// Facility code
#define ELAF_GENERAL                              1
#define ELAF_SYS                                  2
#define ELAF_HTTP                                 3
#define ELAF_RESERVED2                            4
#define ELAF_ICE                                  5
#define ELAF_DHT                                  6


#define ELAERR_INVALID_ARGS                       1
#define ELAERR_OUT_OF_MEMORY                      2
#define ELAERR_BUFFER_TOO_SMALL                   3
#define ELAERR_BAD_PERSISTENT_DATA                4
#define ELAERR_INVALID_PERSISTENCE_FILE           5
#define ELAERR_INVALID_CONTROL_PACKET             6
#define ELAERR_INVALID_CREDENTIAL                 7
#define ELAERR_SERVER_FAILED                      8
#define ELAERR_ALREADY_RUN                        9
#define ELAERR_NOT_READY                          10
#define ELAERR_NOT_EXIST                          11
#define ELAERR_ALREADY_EXIST                      12
#define ELAERR_NO_MATCHED_REQUEST                 13
#define ELAERR_INVALID_USERID                     14
#define ELAERR_INVALID_NODEID                     15
#define ELAERR_INVALID_APPID                      16
#define ELAERR_INVALID_DESCRIPTOR                 17
#define ELAERR_WRONG_STATE                        18
#define ELAERR_BUSY                               19
#define ELAERR_LANGUAGE_BINDING                   20
#define ELAERR_ENCRYPT                            21
#define ELAERR_SDP_TOO_LONG                       22
#define ELAERR_INVALID_SDP                        23
#define ELAERR_NOT_IMPLEMENTED                    24
#define ELAERR_LIMIT_EXCEEDED                     25
#define ELAERR_UNKNOWN                            26

#define ELA_MK_ERROR(facility, code)  (0x80000000 | ((facility) << 24) | \
                    ((((code) & 0x80000000) >> 8) | ((code) & 0x7FFFFFFF)))

#define ELA_GENERAL_ERROR(code)       ELA_MK_ERROR(ELAF_GENERAL, code)
#define ELA_SYS_ERROR(code)           ELA_MK_ERROR(ELAF_SYS, code)
#define ELA_HTTP_ERROR(code)          ELA_MK_ERROR(ELAF_HTTP, code)
#define ELA_ICE_ERROR(code)           ELA_MK_ERROR(ELAF_ICE, code)
#define ELA_DHT_ERROR(code)           ELA_MK_ERROR(ELAF_DHT, code)

**Comment by liyangwood** [comment]
@kuit how to fix this error, could you give me a data argument sample?

**Comment by kuit** [comment]
"BLkx8SkBpxxzM9dQwnTFtviboQidgvpAp8nk1CTTZo6Y" is a friend? @liyangwood

**Comment by liyangwood** [comment]
@kuit no, it is just a node id, no any relationship.

**Comment by kuit** [comment]
@liyangwood  you try to use a friend. The doc describe "Send invite request to a friend.".

**Comment by liyangwood** [comment]
Got it, thanks
