### ISSUE TITLE
Send messages - testing process (desktop chat app)

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.NET.Carrier.Nodejs.SDK#24]
On the desktop chat app, I'm wondering what's your process for testing sending messages between users because you can run only one instance with the desktop app, so the other user is always disconnected

chat app looks good 👌

**Comment by liyangwood** [comment]
Hi, chat-app is kind of dapp, no server involved. 
you are right, one app only run one carrier instance,  should run the demo or web demo example to run another instance to message with desktop app.
btw, this is my address Pbq7sRFJY2ywa6ok4XYyMwkgtER3UPghBotccPXp55pxNddbVJrx, welcome to chat me.

**Comment by jmsaulnier** [comment]
@liyangwood Thanks
