### ISSUE TITLE
RFI:(Request for Improvement ) Add a echo bot to reply to everyone like a chating bot for testing

### ISSUE THREAD

**Issue by kevingzhang** [elastos/Elastos.NET.Carrier.Nodejs.SDK#26]
Many people are trying this chat app, but they do not know others, there is no way to one people to test the feature. 
Why do not we create a chatting bot, the simplest one is just echo what you send. 

There are some online chatting bot API if you want to use. At the first step, making an echo is good enough. just for testing.

**Comment by liyangwood** [comment]
there is a robot carrier instance running on the cloud. 
look at readme to find it.

close the issue.
