### ISSUE TITLE
RFI: (Request for improvement). Can we add a notification when new message coming?

### ISSUE THREAD

**Issue by kevingzhang** [elastos/Elastos.NET.Carrier.Nodejs.SDK#27]
Either a desktop notification box or a simple beep sound is OK

**Comment by liyangwood** [comment]
add badge on app icon. 
please test and found it clearly or not.

**Comment by kevingzhang** [comment]
has not tried it yet, but can it show notification even the app is at background?

**Comment by liyangwood** [comment]
@kevingzhang Add desk notification for new incoming message. just like wechat desktop app.

**Comment by liyangwood** [comment]
fix and close the issue.
