### ISSUE TITLE
Cann't build demo on os window10 arch x64

### ISSUE THREAD

**Issue by jerry6290** [elastos/Elastos.NET.Carrier.Nodejs.SDK#30]
* OS Version:  Window10 Professional
* Arch:  x64
* npm --version  5.6.0
* node --version  v9.11.1

Step:
1. git clone https://github.com/elastos/Elastos.NET.Carrier.Nodejs.SDK.git
1. cd example/demo
3. npm install elastos_carrier_addon, build error, the same error message below when build by "npm install"
``` shell
npm WARN ls@1.0.0 No repository field.

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for elastos_carrier_addon@0.0.4: wanted {"os":"darwin,linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

**Comment by kevingzhang** [comment]
Looks the add-on was not compiled or published a windows version.

**Comment by kuit** [comment]
"elastos_carrier_addon" isn't support windows, because carrier SDK isn't support windows at current.

**Comment by liyangwood** [comment]
looks like there was no more comments, close the issue
