### ISSUE TITLE
example/demo how to send file binary butter

### ISSUE THREAD

**Issue by liyangwood** [elastos/Elastos.NET.Carrier.Nodejs.SDK#38]
From demo.js, I found "swrite streamId buffer" could send buffer to node.
when I want to send a file buffer like below
```
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = (e)=>{
          const binary = e.target.result;
          const buffer = new Buffer(binary);

          try{
            // this.$root.getCarrier().execute('stream_write', this.stream.id, new Buffer('aaa'))
            this.$root.getCarrier().execute('stream_write', this.stream.id, buffer)
          }catch(e){
            console.error(e);
          }

        }
```
there will be an error " Error: Run ela_stream_write error:0x81000001 "
and the target node does not receive the data.
but if I use the comment line - "this.$root.getCarrier().execute('stream_write', this.stream.id, new Buffer('aaa'))", target could receive the "aaa".
the stream mode is "plain" and stream type is 'TEXT'.
so is there any condition or limitation to send a buffer?

**Comment by kuit** [comment]
binary is a array type? 
https://nodejs.org/api/buffer.html

**Comment by liyangwood** [comment]
yes, array

**Comment by liyangwood** [comment]
<img width="620" alt="2018-06-08 3 34 17" src="https://user-images.githubusercontent.com/3214173/41145092-8d2aa99a-6b31-11e8-878c-de6bebfa8ac9.png">

Look at this picture. the first buffer is success. target node receive the data "aaa"
the second is showing successfully, but there is an error "Error: Run ela_stream_write error:0x81000001", and target node does not received.

**Comment by kuit** [comment]
Do readAsArrayBuffer return a array, no reader.readAsDataURL?
maybe you should divided the context of the file into smaller, if it's size too large.

**Comment by kuit** [comment]
the buffer size no more than 2K.

**Comment by liyangwood** [comment]
@kuit yes, the size limitation is 2k.  thanks
