### ISSUE TITLE
session request or reply will be failed sometimes

### ISSUE THREAD

**Issue by liyangwood** [elastos/Elastos.NET.Carrier.Nodejs.SDK#39]
<img width="862" alt="2018-06-09 10 05 47" src="https://user-images.githubusercontent.com/3214173/41186653-b5985bca-6bcc-11e8-8dcc-f77d1132352c.png">

Loot at the above pic. It shows the session request and session reply error. Sometimes it will be happen. not every time. 

please check it the reason, maybe it is carrier network problem, but I am not sure.

**Comment by kuit** [comment]
Stream connect steps:
                A                                   B
1               sinit                               sinit
2               snew B_id
3               sadd stream_type_X
4               srequest
5                                                   Reply use following commands:
                                                    1). snew A
                                                    2). sreply refuse [reason]
                                                    OR:
                                                    1). snew A
                                                    2). sadd [plain] [reliable] [multiplexing] [portforwarding]
                                                    3). sreply ok


Note:
step 4 condition:   a. Stream [1] state changed to: initialized
                    b. B connection changed to be online
step 5 3) condition:    a. Stream [1] state changed to: initialized

**Comment by liyangwood** [comment]
I have seen the readme.
this is not the reason of mine. because it happened sometimes, not every time.
I found if I type command sadd and srequest very fast, e.g., like in 2 seconds, the error have a big change to happen.
