### ISSUE TITLE
Carrier Discovery - User Persistence

### ISSUE THREAD

**Issue by ClarenceL** [elastos/Elastos.NET.Carrier.Nodejs.SDK#4]
Couple questions:

1.   How does an application find other applications of like-same type across the carrier? (Discovery)

2.  Is there any way to persist and reuse an `address`, `nodeid` and friend list? Otherwise what is the 
    point of the friend list? My understanding is that the `address` and `nodeid` is private to the 
    carrier and not intended to be used by the application, in that case we need discovery and user 
    management external to the carrier, please let me know if this is correct.
    
    Perhaps in the development pipeline is some integration with the UUID / DID from the blockchain 
    for this purpose?

**Comment by stiartsly** [comment]
1.   Application (as a Carrier Peer) try to find the peer with specific address (including unique UserID) over carrier through DHT protocol. The details about DHT protocol can be found on website.
2.  NodeId(or UserId) is local-cached, but not for address of being renewable, and all friend list  is also local-cached.  NodeID should be public to all friends and address should be all users want to be friends of us.
3. Not totally understand about the purpose of questions.

**Comment by ClarenceL** [comment]
Thanks for your help, my main purpose is to understand how to keep my same identity across multiple devices and even if the carrier node restarts locally. Maybe the only way to do this is with DID from Elastos.RT or create your own user authentication service on Elastos.Carrier?

If I want to create my own services on Carrier I need a static address/nodeId too, how is this done?

Thanks

**Comment by kevingzhang** [comment]
there won't be any authentication service on Carrier. that is not something Carrier supposed to do.
DID was born for this purpose.
