### ISSUE TITLE
Can't use index.js as 'main' to publish

### ISSUE THREAD

**Issue by kuit** [elastos/Elastos.NET.Carrier.Nodejs.SDK#7]
When I use  index.js as 'main' to publish in package.json，it's not work.
After installed, and run demo.js :
Error: Cannot find module './linux/elac'

**Comment by kuit** [comment]
Sorry, I forget @ you. @kevingzhang

**Comment by kevingzhang** [comment]
please follow the instruction and try it. I know you have fixed this issue. please close when done

**Comment by kuit** [comment]
misspelled: './linux/elac' => './linux/eca'
