### ISSUE TITLE
Cannot npm install addon

### ISSUE THREAD

**Issue by kevingzhang** [elastos/Elastos.NET.Carrier.Nodejs.SDK#8]

**Comment by kevingzhang** [comment]
Kevins-MacBook-Pro:demo kevinzhang$ npm i elastos_carrier_addon
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "elastos_carrier_addon" under a package
npm ERR! also called "elastos_carrier_addon". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kevinzhang/.npm/_logs/2018-04-11T16_27_49_308Z-debug.log
Kevins-MacBook-Pro:demo kevinzhang$

**Comment by kuit** [comment]
1:"https://www.npmjs.com/package/elastos_carrier_addon",  it's exist.
2: Maybe the error need the node version ">=9.9.0"
  I use:
 "engines": {
    "node": ">=9.9.0"
  }
in package.json.

**Comment by kuit** [comment]
Jingyu and I both can install and run demo.js.

**Comment by kevingzhang** [comment]
problem fixed after update. the new code works fine. thanks
